### ISSUE TITLE
is ansible 1.9.6 supported ?

### ISSUE THREAD

**Issue by acomisario** [sadsfae/ansible-elk#56]
Hi.

Trying to use on RHEL 7 using ansible 1.9.6.
The task 

TASK: [logstash | Load filebeat JSON index template] **************************

Gives a timeout, if i execute this with Ansible to keep temporary files, and execute the ansible resulting python the error is as follow:

python -tt /root/.ansible/tmp/ansible-tmp-1507310163.34-85406240056390/uri
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1507310163.34-85406240056390/uri", line 2106, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1507310163.34-85406240056390/uri", line 415, in main
    resp, content, dest = uri(module, url, dest, user, password, body, method, dict_headers, redirects, socket_timeout, validate_certs)
  File "/root/.ansible/tmp/ansible-tmp-1507310163.34-85406240056390/uri", line 311, in uri
    resp, content = h.request(url, method=method, body=body, headers=headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1621, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1363, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1285, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1017, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 1051, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 1013, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 868, in _send_output
    self.send(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 840, in send
    self.sock.sendall(data)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
TypeError: must be string or buffer, not dict

Maybe the json file's body has an issue, can somebody help me? i need to use ansible 1.9.6
Thanks.

**Comment by sadsfae** [comment]
I recall this working fine in the 1.9 series but have added some ```urllib``` specific timeout / service checks since then and frankly haven't tested it.

```Ansible 2.4.0.0-5.el7``` ships with CentOS7, are you on something older than that?

**Comment by acomisario** [comment]
Yes, using 1.9.6 on RHEL 7.3

**Comment by sadsfae** [comment]
Ok, by all manner this should work fine as it's what I test with, I started off with EL7.2 and now test currently against EL7.4.  The current version of Ansible in EL7 is ```2.4.0``` are you limited to ```1.9.6``` for some reason and could you test the former to see if it's some kind of regression?
